# Install the course conda environment by running 
# the following command in your conda base environment:
# conda env create -f enviroment.yml
name: 'heart_att'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib>=3.2.2
  - altair_saver
  - pandas==1.5.1
  - dataframe-image==0.1.3
  - docopt==0.7.1
  - altair_saver==0.1.0
  - ipython==7.10.1
  
